# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
