# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20171204_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
            ],
            options={
                'ordering': ['file_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['start_date']},
        ),
    ]
